CREATE ROLE app_group WITH
    NOSUPERUSER
    NOCREATEDB
    NOCREATEROLE
    NOINHERIT
    NOLOGIN
    NOREPLICATION
    NOBYPASSRLS
    CONNECTION LIMIT -1;

GRANT app_group to devops;

CREATE ROLE flyway WITH
    NOSUPERUSER
    NOCREATEDB
    NOCREATEROLE
    INHERIT
    LOGIN
    NOREPLICATION
    NOBYPASSRLS
    CONNECTION LIMIT -1
    password 'flyway';

GRANT app_group to flyway;

GRANT ALL PRIVILEGES ON DATABASE devops TO app_group;

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE SCHEMA flyway AUTHORIZATION app_group;
GRANT ALL PRIVILEGES ON SCHEMA flyway to app_group;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA flyway to app_group;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA flyway to app_group;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA flyway to app_group;
GRANT ALL PRIVILEGES ON ALL PROCEDURES IN SCHEMA flyway to app_group;
GRANT ALL PRIVILEGES ON ALL ROUTINES IN SCHEMA flyway to app_group;

