spring.application.name=project
spring.datasource.url=jdbc:postgresql://${DB_HOST}:5432/${DB_BASE}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.devtools.restart.poll-interval=1000
spring.devtools.restart.quiet-period=400
spring.devtools.restart.trigger-file=.restart-trigger
spring.devtools.livereload.enabled=true